### ISSUE TITLE
Undelegating the Max amount does not interact with Keplr

### ISSUE THREAD

**Issue by TJ-BitCanna** [BitCannaGlobal/WeedWallet#158]
![image](https://github.com/BitCannaGlobal/WeedWallet/assets/112879218/d887f8c7-c70d-4d9d-9f60-7603fc0c6085)

The "Undelegate" button does not send something to Keplr if you undelegate the whole bonded amount. 

If I try to undelegate this whole amount from StakeWolle (who left our network quietly it seems) I don't get the Keplr pop-up. 
I've tried using the max button as well as typing the amount.

Undelegating 1 BCNA works, but not the complete amount.

**Comment by RaulBernal** [comment]
It works! I tried to undelegate MAX and worked. 
When you face an issue try to open the "inspector" at browser to try to find the error @TJ-BitCanna  :)
<img width="1158" alt="image" src="https://github.com/BitCannaGlobal/WeedWallet/assets/3751926/19d8675b-caf4-4cb9-9baf-a1f197fc86c1">
https://testnet.ping.pub/bitcanna/tx/601649FCBF8DD59F1485A5E02A05EF03B92297021846E2683168E4FF1DC018BD
<img width="1015" alt="image" src="https://github.com/BitCannaGlobal/WeedWallet/assets/3751926/1f3a1f9a-17e1-4ace-8624-57bec29380b7">
