### ISSUE TITLE
v3. Main page. Claim action didn't receive memo field.

### ISSUE THREAD

**Issue by RaulBernal** [BitCannaGlobal/WeedWallet#167]
At main page, when you click at CLAIM button and fill the memo field at the form it is not transferred to Keplr memo field.
<img width="347" alt="image" src="https://github.com/BitCannaGlobal/WeedWallet/assets/3751926/8484159a-8da4-4c7a-b4a3-2c9c0a96bddc">

So we have two options here:

1. Remove the memo field at the form (because to put a note here is not important)   or, 
2. Make it works and transfer the memo/note from form to Kplr.

**Comment by atmoner** [comment]
True!
Fixed here: https://github.com/BitCannaGlobal/WeedWallet/commit/0d7e3ac8e3ca25b6c95e71a1428c0be91fb985d0

**Comment by RaulBernal** [comment]
Fixed! good one!
https://testnet.ping.pub/bitcanna/tx/630AFD1F846071656ACCEDD0B9A083CBC5C4C08A3012A124FA7530D5795209A4
