### ISSUE TITLE
v3. Main page. Available balance in popup to delegate.

### ISSUE THREAD

**Issue by El-Jay-Crypto** [BitCannaGlobal/WeedWallet#168]
![Screenshot from 2023-11-13 12-48-16](https://github.com/BitCannaGlobal/WeedWallet/assets/22987129/81ba6bb5-c9dd-4c43-98c7-0ca80a72701e)
The available amount of your balance to stake doesn't  show up correct in this pop-up. While you can see there is an amount available on the right. Clicking the max button does nothing either. 
(Tested in Brave brower Version 1.59.117 Chromium: 118.0.5993.70)

**Comment by atmoner** [comment]
> The available amount of your balance to stake doesn't show up correct in this pop-up. While you can see there is an amount available on the right. Clicking the max button does nothing either. (Tested in Brave brower Version 1.59.117 Chromium: 118.0.5993.70)

Yes, this is a problem that I have already detected!
When you arrive on the dashboard, change pages, come back to the dashboard and try again!
