### ISSUE TITLE
v3. GOV. Deposit period actions are not coded

### ISSUE THREAD

**Issue by RaulBernal** [BitCannaGlobal/WeedWallet#176]
In Deposit period, we need to add actions for: 
* Add more deposit coins
* ??

<img width="1327" alt="image" src="https://github.com/BitCannaGlobal/WeedWallet/assets/3751926/5bf089f0-c23e-45e4-8e07-1450e54fe864">

**Comment by atmoner** [comment]
@RaulBernal  The deposit is not necessary on the ui, this risks leading the user to make an error...
I suggested it at the time but it is not necessary.

I added a message to replace the date if it is in deposit period

![image](https://github.com/BitCannaGlobal/WeedWallet/assets/1071490/897ef5f8-2882-48c8-a9f9-15b118298aed)
Fixed here: https://github.com/BitCannaGlobal/WeedWallet/commit/6c1c417b0cf813b273d8c24d66a15ce5c38a1eed

**Comment by RaulBernal** [comment]
Sorry the misunderstanding @atmoner I'm going to close as duplicated.
